# Generated by Django 5.2.17 on 2026-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
